{
 "title": "BOE",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from boe with key = \"env\""
   },
   {
    "name": "sia",
    "label": "BOE Server",
    "query": "show tag values from boe with key = \"boe_sia\" where env =~ /$env/"
   }
  ]
 },
 "panels": [
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BOE Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "boe_sia" ], "type": "tag" },
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "measurement": "boe",
     "query": "SELECT * FROM \"monitoring\".\"boe\" WHERE (\"env\" =~ /^$env$/ AND \"boe_sia\" =~ /^$sia$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cpu_pcnt" ], "type": "field" }
      ],
      [
       { "params": [ "mem_pcnt" ], "type": "field" }
      ],
      [
       { "params": [ "rsz" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "vsz" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "boe_sia", "operator": "=~", "value": "/^$sia$/" }
     ]
    }
   ]
  },
  {
   "title": "Peak MEM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Peak Usage (%)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "boe_sia" ], "type": "tag" }
     ],
     "measurement": "boe",
     "query": "SELECT max(\"mem_pcnt\") FROM \"boe\" WHERE (\"env\" =~ /^$env$/ AND \"boe_sia\" =~ /^$sia$/) AND $timeFilter GROUP BY time(15m), \"env\", \"boe_sia\"",
     "select": [
      [
       { "params": [ "mem_pcnt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "MEM " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "boe_sia", "operator": "=~", "value": "/^$sia$/" },
      { "condition": "AND", "key": "mem_pcnt", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Peak CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Peak Usage (%)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "boe_sia" ], "type": "tag" }
     ],
     "measurement": "boe",
     "query": "SELECT \"cpu_pcnt\" AS \"CPU %\" FROM \"boe\" WHERE (\"env\" =~ /^$env$/ AND \"boe_sia\" =~ /^$sia$/ AND \"cpu_pcnt\" > 0) AND $timeFilter GROUP BY \"host\", \"env\", \"boe_sia\"",
     "select": [
      [
       { "params": [ "cpu_pcnt" ], "type": "field" },
       { "params": [ "CPU %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "boe_sia", "operator": "=~", "value": "/^$sia$/" },
      { "condition": "AND", "key": "cpu_pcnt", "operator": ">", "value": "0" }
     ]
    }
   ]
  }
 ]
}