{
 "title": "FM",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from fm_active_alarms_per_hour with key =\"env\""
   }
  ]
 },
 "panels": [
  {
   "title": "Alarm Stats ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "alarms_per_hour",
     "measurement": "fm_active_alarms_per_hour",
     "select": [
      [
       { "params": [ "num_active_alarm" ], "type": "field" },
       { "params": [ "alarms_per_hour" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Stats",
   "type": "graph",
   "description": "Events per sec on FM engine ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "events_per_min",
     "measurement": "fm_events_per_second",
     "select": [
      [
       { "params": [ "events_per_min" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "FM Queue Size",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "wl_server" ], "type": "tag" }
     ],
     "measurement": "wls_queue_status",
     "select": [
      [
       { "params": [ "queue_size" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "wl_server", "operator": "!=", "value": "SI" },
      { "condition": "AND", "key": "wl_server", "operator": "!=", "value": "RCA" },
      { "condition": "AND", "key": "state", "operator": "!=", "value": "OK" }
     ]
    }
   ]
  }
 ]
}