{
 "title": "Hadoop",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from cloudera_events with key = \"env\""
   },
   {
    "name": "cloudera",
    "label": "Cloudera",
    "query": "show tag values from cloudera_events with key = \"cloudera\" where env =~ /$env/"
   },
   {
    "name": "alert",
    "label": "Alert",
    "query": "show tag values from cloudera_events with key = \"alert\" where env =~ /$env/ and cloudera =~ /$cloudera/"
   },
   {
    "name": "message",
    "label": "Message",
    "query": "select distinct(message) from cloudera_events"
   },
   {
    "name": "hdfs_namenode",
    "label": "HDFS Node",
    "query": "show tag values from hdfs_total_utilization with key = \"hdfs_namenode\""
   }
  ]
 },
 "panels": [
  { "title": "Impala", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HDFS: Total Utilization (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Capacity (GB)" }
   ],
   "targets": [
    {
     "measurement": "hdfs_total_utilization",
     "query": "SELECT \"dfs_capacity\" AS \"HDFS Total\", \"dfs_capacity_used\" AS \"HDFS Used\" FROM \"monitoring\".\"hdfs_total_utilization\" WHERE (\"cloudera\" =~ /^$cloudera$/ AND \"env\" =~ /^$env$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "dfs_capacity" ], "type": "field" },
       { "params": [ "HDFS Total" ], "type": "alias" }
      ],
      [
       { "params": [ "dfs_capacity_used" ], "type": "field" },
       { "params": [ "HDFS Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "hdfs_namenode", "operator": "=~", "value": "/^$hdfs_namenode$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS: Total Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Utilization (%)" }
   ],
   "targets": [
    {
     "measurement": "hdfs_total_utilization",
     "query": "SELECT \"dfs_capacity\" AS \"HDFS Total\", \"dfs_capacity_used\" AS \"HDFS Used\" FROM \"monitoring\".\"hdfs_total_utilization\" WHERE (\"cloudera\" =~ /^$cloudera$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "dfs_capacity_pcnt" ], "type": "field" },
       { "params": [ "HDFS Util%l" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "hdfs_namenode", "operator": "=~", "value": "/^$hdfs_namenode$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS: PM Utilization (MB)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Size (MB)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "hdfs_partition" ], "type": "tag" },
      { "params": [ "hdfs_pm" ], "type": "tag" }
     ],
     "measurement": "hdfs_pm_utilization",
     "query": "SELECT \"hdfs_consumed\"  / 1024.0/1024.0 /*, \"hdfs_total\"  / 1024.0/1024.0*/ FROM \"monitoring\".\"hdfs_pm_utilization\" WHERE (\"env\" =~ /^$env$/ AND \"hdfs_namenode\" =~ /^$hdfs_namenode$/) AND $timeFilter GROUP BY \"hdfs_partition\", \"hdfs_pm\"",
     "select": [
      [
       { "params": [ "hdfs_consumed" ], "type": "field" },
       { "params": [ " / 1024.0/1024.0" ], "type": "math" }
      ],
      [
       { "params": [ "hdfs_total" ], "type": "field" },
       { "params": [ " / 1024.0/1024.0" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "hdfs_namenode", "operator": "=~", "value": "/^$hdfs_namenode$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS: PM Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Util (%)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "hdfs_partition" ], "type": "tag" },
      { "params": [ "hdfs_pm" ], "type": "tag" }
     ],
     "measurement": "hdfs_pm_utilization",
     "query": "SELECT 100*hdfs_consumed/hdfs_total FROM \"monitoring\".\"hdfs_pm_utilization\" WHERE (\"env\" =~ /^$env$/ AND \"hdfs_namenode\" =~ /^$hdfs_namenode$/) AND $timeFilter GROUP BY \"hdfs_partition\", \"hdfs_pm\"",
     "select": [
      [
       { "params": [ "hdfs_consumed" ], "type": "field" },
       {
        "params": [
         " 100 /hds_total / 1024.0/1024.0"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "hdfs_namenode", "operator": "=~", "value": "/^$hdfs_namenode$/" }
     ]
    }
   ]
  },
  {
   "title": "Impala DB: Listener Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "impala" ], "type": "tag" }
     ],
     "measurement": "impala_connectivity",
     "select": [
      [
       { "params": [ "db_status" ], "type": "field" }
      ],
      [
       { "params": [ "latency_ms" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Impala:  Data Consistency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "impala_data_consistency",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Impala DB: Fetch Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "impala_fetch_time",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Impala:  Top PM Data Amount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "impala_pm_data",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Cloudera", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Events By Category",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Events#" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "cloudera_events",
     "query": "SELECT count(\"message\") AS \"Events\" FROM \"monitoring\".\"cloudera_events\" WHERE (\"cloudera\" =~ /^$cloudera$/ AND \"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1h), \"categoty\"",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cloudera", "operator": "=~", "value": "/^$cloudera$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Events By Severity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Events#" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "alert" ], "type": "tag" }
     ],
     "measurement": "cloudera_events",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cloudera", "operator": "=~", "value": "/^$cloudera$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloudera Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cloudera" ], "type": "tag" },
      { "params": [ "category" ], "type": "tag" },
      { "params": [ "alert" ], "type": "tag" }
     ],
     "measurement": "cloudera_events",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       { "params": [ "Message" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "cloudera", "operator": "=~", "value": "/^$cloudera$/" },
      { "condition": "AND", "key": "alert", "operator": "=~", "value": "/^$alert$/" }
     ]
    }
   ]
  }
 ]
}