{
 "title": "Kubernetes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag  values from kubernetes_node with key = \"cluster\""
   },
   {
    "name": "node",
    "label": "Node",
    "query": "show tag values from kubernetes_node with key = \"node\" where cluster =~ /$cluster/"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "show tag values from kubernetes_pod with key = \"pod\" where cluster =~ /$cluster/"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "show tag values from kubernetes_container with key = \"container\" where cluster =~ /$cluster/"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_container",
     "select": [
      [
       { "params": [ "cpu_usage_seconds_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Memory (Bytes)" ], "type": "alias" }
      ],
      [
       { "params": [ "network_receive_bytes_tota" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Received (Bytes)" ], "type": "alias" }
      ],
      [
       { "params": [ "network_transmit_bytes_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Transmit (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "container", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_container",
     "select": [
      [
       { "params": [ "cpu_usage_seconds_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "container", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_container",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Memory (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "container", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  },
  {
   "title": "Container Network Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_container",
     "select": [
      [
       { "params": [ "network_receive_bytes_tota" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Received (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "container", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  },
  {
   "title": "Container Network Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_container",
     "select": [
      [
       { "params": [ "network_transmit_bytes_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Transmitted (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "container", "operator": "=~", "value": "/^$container$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod",
     "select": [
      [
       { "params": [ "cpu_usage_seconds_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Memory (bytes)" ], "type": "alias" }
      ],
      [
       { "params": [ "network_receive_bytes_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Received (bytes)" ], "type": "alias" }
      ],
      [
       { "params": [ "network_transmit_bytes_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Transmitted (bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$pod$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod",
     "select": [
      [
       { "params": [ "cpu_usage_seconds_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$pod$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Memory (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$pod$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod Network Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod",
     "select": [
      [
       { "params": [ "network_receive_bytes_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Received (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$pod$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod Network Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod",
     "select": [
      [
       { "params": [ "network_transmit_bytes_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Received (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "pod", "operator": "=~", "value": "/^$pod$/" }
     ]
    }
   ]
  },
  {
   "title": "Node metrics",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "cpu_usage_seconds_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Memory (bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Memory (Bytes)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "cpu_usage_seconds_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}