{
 "title": "Main Alerts Screen",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "SHOW TAG VALUES FROM  helix_alerts  WITH KEY = \"env\""
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM  helix_alerts  WITH KEY = \"host\"  where  env =~ /$env/"
   },
   {
    "name": "managed_object",
    "label": "Managed Object",
    "query": "show tag values from helix_alerts with key = \"managed_object\"  "
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "show tag values from helix_alerts with key = \"metric\" where env =~ /$env/ and host =~ /$host/ "
   },
   {
    "name": "source",
    "label": "Source",
    "query": "show tag values from  helix_alerts with key = \"source\" where env =~ /$env/ "
   },
   {
    "name": "severity_num",
    "query": "show tag values from forever.helix_alert_severity with key = \"num\"  where text =~ /$severity_text/"
   },
   {
    "name": "severity_text",
    "label": "Severity",
    "query": "show tag values from forever.helix_alert_severity with key = \"text\""
   }
  ]
 },
 "panels": [
  {
   "title": "Minor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "[[tag_severity]]",
     "groupBy": [
      { "params": [ "severity" ], "type": "tag" }
     ],
     "measurement": "helix_alerts",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"message\") FROM helix_alerts GROUP BY env, host, source, managed_object, metric, severity) WHERE (\"env\" =~ /^$env$/ AND \"severity\" = '1' AND $timeFilter) group by severity\n",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1h" },
      { "condition": "AND", "key": "severity", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Major",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "[[tag_severity]]",
     "groupBy": [
      { "params": [ "severity" ], "type": "tag" }
     ],
     "measurement": "helix_alerts",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"message\") FROM helix_alerts GROUP BY env, host, source, managed_object, metric, severity) WHERE (\"env\" =~ /^$env$/ AND \"severity\" = '2' AND $timeFilter) group by severity",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1h" },
      { "condition": "AND", "key": "severity", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "[[tag_severity]]",
     "groupBy": [
      { "params": [ "severity" ], "type": "tag" }
     ],
     "measurement": "helix_alerts",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"message\") FROM helix_alerts GROUP BY env, host, source, managed_object, metric, severity) WHERE (\"env\" =~ /^$env$/ AND \"severity\" = '3' AND $timeFilter) group by severity",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1h" },
      { "condition": "AND", "key": "severity", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Alerts by env",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_env]]",
     "groupBy": [
      { "params": [ "env" ], "type": "tag" }
     ],
     "measurement": "helix_alerts",
     "query": "select count(\"message\") as \"count\" from (select last(\"message\") as \"message\" from helix_alerts WHERE (\"env\" =~ /^$env$/ AND $timeFilter) GROUP BY \"env\", \"host\", \"managed_object\", \"metric\", \"source\") group by \"env\"\n",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "env" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1h" }
     ]
    }
   ]
  },
  {
   "title": "Alerts by metric",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_metric]]",
     "groupBy": [
      { "params": [ "metric" ], "type": "tag" }
     ],
     "measurement": "helix_alerts",
     "query": "select count(\"message\") as \"count\" from (select last(\"message\") as \"message\" from helix_alerts WHERE (\"env\" =~ /^$env$/ AND $timeFilter) GROUP BY \"env\", \"host\", \"managed_object\", \"metric\", \"source\") group by \"metric\"",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 1h" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "managed_object" ], "type": "tag" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "helix_alerts",
     "query": "SELECT last(\"alert_state\") AS \"Alert\" FROM \"teoco_hm_alertlog\" WHERE (\"env\" =~ /^$env$/ AND \"host\" =~ /^$host$/ AND \"managed_object\" =~ /^$managed_object$/ AND \"metric\" =~ /^$metric$/) AND $timeFilter GROUP BY \"env\", \"host\", \"managed_object\", \"metric\", \"alert\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "severity" ], "type": "field" },
       { "params": [ "Severity" ], "type": "alias" }
      ],
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Message" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "managed_object", "operator": "=~", "value": "/^$managed_object$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^$metric$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity_num$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  }
 ]
}