{
 "title": "Mediation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from dvx_lib_conductor_stat with key = \"env\""
   },
   {
    "name": "conductor_instance",
    "label": "INSTANCE",
    "query": "show tag values from dvx_lib_conductor_stat with key = \"conductor_inst\" where env =~ /$env/"
   }
  ]
 },
 "panels": [
  { "title": "Libraries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DVX Library Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "conductor_host" ], "type": "tag" },
      { "params": [ "conductor_instance" ], "type": "tag" },
      { "params": [ "dvx_chain" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "dvx_lib_queue_stat",
     "select": [
      [
       { "params": [ "valid" ], "type": "field" }
      ],
      [
       { "params": [ "waits" ], "type": "field" }
      ],
      [
       { "params": [ "recieved" ], "type": "field" }
      ],
      [
       { "params": [ "recs_per_sec" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "conductor_instance", "operator": "=~", "value": "/^$conductor_instance$/" }
     ]
    }
   ]
  },
  {
   "title": "LIB: CPU/Memory Stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "conductor_host" ], "type": "tag" },
      { "params": [ "conductor_instance" ], "type": "tag" },
      { "params": [ "conductor_pid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "dvx_lib_cpu_mem_stat",
     "query": "SELECT * FROM \"monitoring\".\"dvx_lib_cpu_mem_stat\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cpu_pcnt" ], "type": "field" }
      ],
      [
       { "params": [ "memory_kb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "conductor_instance", "operator": "=~", "value": "/^$conductor_instance$/" }
     ]
    }
   ]
  },
  {
   "title": "File Collection daily",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "rdr_access" ], "type": "tag" },
      { "params": [ "severity" ], "type": "tag" }
     ],
     "measurement": "dvx_rdr_stat",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "LIB: CPU Stats",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "conductor_instance" ], "type": "tag" }
     ],
     "measurement": "dvx_lib_cpu_mem_stat",
     "select": [
      [
       { "params": [ "cpu_pcnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "conductor_instance", "operator": "=~", "value": "/^$conductor_instance$/" }
     ]
    }
   ]
  }
 ]
}