{
 "title": "Oracle DB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from oracle_status with key = \"env\""
   },
   {
    "name": "sid",
    "label": "Oracle SID",
    "query": "show tag values from oracle_status with key = \"sid\" where env =~/$env/"
   },
   {
    "name": "tablespace",
    "label": "Tablespace",
    "query": "show tag values from oracle_tablespace with key = \"tablespace\" where env =~/$env/"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB Listener Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "env" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "sid" ], "type": "tag" }
       ],
       "measurement": "oracle_listener_status",
       "select": [
        [
         { "params": [ "latency_ms" ], "type": "field" }
        ],
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    },
    {
     "title": "DB Listener Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Latency (ms)" }
     ],
     "targets": [
      {
       "measurement": "oracle_listener_status",
       "select": [
        [
         { "params": [ "latency_ms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    },
    {
     "title": "DB Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "instance_name" ], "type": "tag" },
        { "params": [ "status" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "oracle_db_info",
       "select": [
        [
         { "params": [ "version" ], "type": "field" }
        ],
        [
         { "params": [ "instance_number" ], "type": "field" }
        ],
        [
         { "params": [ "startup_time" ], "type": "field" }
        ],
        [
         { "params": [ "shutdown_time" ], "type": "field" }
        ],
        [
         { "params": [ "parallel" ], "type": "field" }
        ],
        [
         { "params": [ "shutdown_pending" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "instance_name", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    },
    {
     "title": "Oracle RMAN Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "managed_object" ], "type": "tag" },
        { "params": [ "severity" ], "type": "tag" }
       ],
       "measurement": "helix_alerts",
       "query": "SELECT \"message\" FROM \"monitoring\".\"helix_alerts\" WHERE (\"source\" = 'oracle_rman_status' AND \"env\" =~ /^$env$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"host\", \"metric\", \"source\", \"managed_object\", \"severity\"",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "oracle_rman_status" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    },
    {
     "title": "Oracle EXP BackUp Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "source" ], "type": "tag" },
        { "params": [ "managed_object" ], "type": "tag" },
        { "params": [ "severity" ], "type": "tag" }
       ],
       "measurement": "helix_alerts",
       "query": "SELECT \"message\" FROM \"monitoring\".\"helix_alerts\" WHERE (\"source\" = 'oracle_rman_status' AND \"env\" =~ /^$env$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"host\", \"metric\", \"source\", \"managed_object\", \"severity\"",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "oracle_exp_backup_status" },
        { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Active Sessions (ASH)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sid" ], "type": "tag" },
      { "params": [ "env" ], "type": "tag" }
     ],
     "measurement": "oracle_ash_top_events",
     "select": [
      [
       { "params": [ "event" ], "type": "field" }
      ],
      [
       { "params": [ "total_sec" ], "type": "field" }
      ],
      [
       { "params": [ "aas" ], "type": "field" }
      ],
      [
       { "params": [ "event_pcnt" ], "type": "field" }
      ],
      [
       { "params": [ "last_seen" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Number Of Sessions Per Wait Class/State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Sessions#" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "wait_class" ], "type": "tag" }
     ],
     "measurement": "oracle_ash_by_class",
     "select": [
      [
       { "params": [ "session_num" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "wait_class", "operator": "!=", "value": "Configuration" }
     ]
    }
   ]
  },
  {
   "title": "Long Queries/Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Long Running Operations",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "measurement": "oracle_long_running_operations",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    },
    {
     "title": "Long Running Queries",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "sql_id" ], "type": "tag" },
        { "params": [ "env" ], "type": "tag" },
        { "params": [ "sid" ], "type": "tag" },
        { "params": [ "serial" ], "type": "tag" }
       ],
       "measurement": "oracle_long_running_queries",
       "query": "SELECT \"wait_sec\", \"sql_id\" , \"sql_text\", \"program\", \"username\", \"status\", \"machine\", \"process\", \"port\" FROM \"monitoring\".\"oracle_long_running_queries\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "wait_sec" ], "type": "field" }
        ],
        [
         { "params": [ "sql_text" ], "type": "field" }
        ],
        [
         { "params": [ "program" ], "type": "field" }
        ],
        [
         { "params": [ "username" ], "type": "field" }
        ],
        [
         { "params": [ "status" ], "type": "field" }
        ],
        [
         { "params": [ "machine" ], "type": "field" }
        ],
        [
         { "params": [ "process" ], "type": "field" }
        ],
        [
         { "params": [ "port" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dbsid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Top Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top50 Locks",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "session_id" ], "type": "tag" },
        { "params": [ "wait_class" ], "type": "tag" },
        { "params": [ "session_state" ], "type": "tag" },
        { "params": [ "serial" ], "type": "tag" },
        { "params": [ "sql_id" ], "type": "tag" },
        { "params": [ "wait_class" ], "type": "tag" }
       ],
       "measurement": "oracle_topN_locks",
       "select": [
        [
         { "params": [ "waited_sec" ], "type": "field" }
        ],
        [
         { "params": [ "module" ], "type": "field" }
        ],
        [
         { "params": [ "program" ], "type": "field" }
        ],
        [
         { "params": [ "machine" ], "type": "field" }
        ],
        [
         { "params": [ "Blocking_Session" ], "type": "field" }
        ],
        [
         { "params": [ "Blocking_Session_Serial" ], "type": "field" }
        ],
        [
         { "params": [ "Blocking_Session_Status" ], "type": "field" }
        ],
        [
         { "params": [ "sql" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Db Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tablespace usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "env" ], "type": "tag" },
        { "params": [ "tablespace" ], "type": "tag" }
       ],
       "measurement": "oracle_tablespace",
       "query": "SELECT \"used_pcnt\" AS \"Used percent\", \"alloc_mb\" AS \"Alloc MB\", \"used_mb\" AS \"Used MB\", \"free_mb\" AS \"Free MB\", \"datfiles_num\" AS \"DataFiles#\" FROM \"monitoring\".\"oracle_tablespace\" WHERE (\"env\" =~ /^$env$/ AND \"tablespace\" =~ /^$tablespace$/ AND \"dbsid\" =~ /^$sid$/) AND $timeFilter GROUP BY \"env\", \"tablespace\"",
       "select": [
        [
         { "params": [ "used_pcnt" ], "type": "field" },
         { "params": [ "Used percent" ], "type": "alias" }
        ],
        [
         { "params": [ "alloc_mb" ], "type": "field" },
         { "params": [ "Alloc MB" ], "type": "alias" }
        ],
        [
         { "params": [ "used_mb" ], "type": "field" },
         { "params": [ "Used MB" ], "type": "alias" }
        ],
        [
         { "params": [ "free_mb" ], "type": "field" },
         { "params": [ "Free MB" ], "type": "alias" }
        ],
        [
         { "params": [ "datfiles_num" ], "type": "field" },
         { "params": [ "DataFiles#" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "tablespace", "operator": "=~", "value": "/^$tablespace$/" },
        { "condition": "AND", "key": "dbsid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    },
    {
     "title": "Invalid Objects",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "measurement": "oracle_invalid_objects",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dbsid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    },
    {
     "title": "MV Refresh",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "measurement": "oracle_mv_refresh",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "dbsid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Paritioning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Partition & Thinout Duplications",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "helix_alerts",
     "query": "SELECT * FROM \"monitoring\".\"helix_alerts\" WHERE (\"source\" = 'oracle_partition_active_thinout' AND \"env\" =~ /^$env$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "oracle_partition_active_thinout"
      },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Parition Alert Log",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "oracle_partition_log",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Records Stat - Huge Non-Partitioned",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "measurement": "oracle_avg_records_stat",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "table",
     "description": "Session statistics",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "measurement": "oracle_sessions",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    },
    {
     "title": "Scheduler Jobs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "measurement": "oracle_scheduler_jobs",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    },
    {
     "title": "Procedures",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "measurement": "oracle_procedures",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}