{
 "title": "PM",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from pm_vip_tables with key = \"env\""
   },
   {
    "name": "sid",
    "label": "Oracle SID",
    "query": "show tag values from pm_vip_tables with key = \"sid\"  where env =~ /$env/"
   }
  ]
 },
 "panels": [
  { "title": "Oracle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oracle DB: Data Amount(24Hr)",
   "type": "graph",
   "description": "Data amount inserted in the last 1 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_tablename:$col",
     "groupBy": [
      { "params": [ "dbhost" ], "type": "tag" },
      { "params": [ "tablename" ], "type": "tag" }
     ],
     "measurement": "pm_data_amount",
     "select": [
      [
       { "params": [ "data_amout" ], "type": "field" },
       { "params": [ "Amount" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "PM Access Files",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pm_access" ], "type": "tag" },
      { "params": [ "severity" ], "type": "tag" }
     ],
     "measurement": "pm_filecoll_status",
     "select": [
      [
       { "params": [ "today_files" ], "type": "field" }
      ],
      [
       { "params": [ "yesterday_files" ], "type": "field" }
      ],
      [
       { "params": [ "msg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "dbhost" ], "type": "tag" },
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "schema" ], "type": "tag" },
      { "params": [ "sid" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "tablename" ], "type": "tag" }
     ],
     "measurement": "pm_overall_status",
     "query": "SELECT \"avg_consist_pct\", \"max_consist_pct\", \"min_consist_pct\" FROM \"long_retention\".\"pm_overall_status\" WHERE $timeFilter GROUP BY \"dbhost\", \"env\", \"host\", \"schema\", \"sid\", \"status\", \"tablename\"",
     "select": [
      [
       { "params": [ "avg_consist_pct" ], "type": "field" }
      ],
      [
       { "params": [ "max_consist_pct" ], "type": "field" }
      ],
      [
       { "params": [ "min_consist_pct" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
     ]
    }
   ]
  },
  {
   "title": "VIP Tables Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tablename" ], "type": "tag" },
      { "params": [ "dbhost" ], "type": "tag" }
     ],
     "measurement": "pm_vip_tables",
     "query": "SELECT \"st_num\", \"today\", \"yesterday\", \"avg_weekly\", \"diff_pcnt\", \"avg_reliability\" FROM \"long_retention\".\"pm_vip_tables\" WHERE (\"env\" =~ /^$env$/ AND \"sid\" =~ /^$sid$/ ) AND $timeFilter GROUP BY \"tablename\", \"dbhost\"",
     "select": [
      [
       { "params": [ "st_num" ], "type": "field" }
      ],
      [
       { "params": [ "today" ], "type": "field" }
      ],
      [
       { "params": [ "yesterday" ], "type": "field" }
      ],
      [
       { "params": [ "avg_weekly" ], "type": "field" }
      ],
      [
       { "params": [ "diff_pcnt" ], "type": "field" }
      ],
      [
       { "params": [ "avg_reliability" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sid", "operator": "=~", "value": "/^$sid$/" },
      { "condition": "AND", "key": "tablename", "operator": "=~", "value": "/^$tablename$/" }
     ]
    }
   ]
  },
  {
   "title": "GAP Monitor : Inconsistency",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "sid" ], "type": "tag" },
      { "params": [ "tablename" ], "type": "tag" }
     ],
     "measurement": "pm_time_gaps",
     "select": [
      [
       { "params": [ "time_gaps" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "sid", "operator": "=~", "value": "/^$sid$/" }
     ]
    }
   ]
  }
 ]
}