{
 "title": "Processes",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from wls_heap_status with key = \"env\""
   },
   {
    "name": "wls",
    "label": "WL Server",
    "query": "show tag values from wls_heap_status with key = \"wl_server\" where env =~ /$env/"
   },
   {
    "name": "n2p_rule",
    "label": "Rule Name",
    "query": "show tag values from helix_n2p_workers with key = \"rule_name\" where env =~/$env/"
   },
   {
    "name": "n2_process",
    "label": "N2 Process",
    "query": "show tag values from helix_n2_status with key = \"n2_process\" where env =~ /$env/"
   },
   {
    "name": "n2_state",
    "label": "N2 State",
    "query": "show tag values from helix_n2_status with key = \"state\" where env =~ /$env/ and n2_process =~ /$n2_process/"
   },
   {
    "name": "jcoreLogs",
    "label": "Jcore Logs",
    "query": "show tag values from helix_jcore_messages with key = \"jcore_log\" where env =~ /$env/"
   }
  ]
 },
 "panels": [
  {
   "title": "Jcore Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JCore  Messages Statistics",
     "type": "table",
     "gridPos": { "h": 13, "w": 14, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "jcore_log" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "helix_jcore_messages",
       "query": "SELECT host, jcore_log as \"JCoreLog\" ,\"message\" as \"Alert\", \"ts_occurred\" as \"Occurred\" FROM \"monitoring\".\"helix_jcore_messages\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ],
        [
         { "params": [ "ts_occurred" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "jcore_log", "operator": "=~", "value": "/^$jcoreLogs$/" }
       ]
      }
     ]
    },
    {
     "title": "JCore Messages Dynamics",
     "type": "graph",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "jcore_log" ], "type": "tag" }
       ],
       "measurement": "helix_jcore_messages",
       "query": "SELECT count(\"message\") FROM \"monitoring\".\"helix_jcore_messages\" WHERE (\"env\" =~ /^$env$/) AND $timeFilter GROUP BY time(1h), \"jcore_log\"",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "jcore_log", "operator": "=~", "value": "/^$jcoreLogs$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "N2 Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "N2 Overview",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "env" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "n2_process" ], "type": "tag" },
        { "params": [ "severity" ], "type": "tag" }
       ],
       "measurement": "helix_n2_status",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "n2_process", "operator": "=~", "value": "/^$n2_process$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$n2_state$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "N2P Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "N2P Overview AGG",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "rule_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "worker_type" ], "type": "tag" }
     ],
     "measurement": "helix_n2p_workers",
     "query": "SELECT \"task_id\", \"wrk_proc_min\", \"wrk_wait_min\" FROM \"monitoring\".\"helix_n2p_workers\" WHERE (\"env\" =~ /^$env$/ AND \"worker_type\" = 'AGG') AND $timeFilter GROUP BY \"env\", \"host\", \"rule_name\", \"state\", \"worker_type\"",
     "select": [
      [
       { "params": [ "task_id" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_proc_min" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_wait_min" ], "type": "field" }
      ],
      [
       { "params": [ "sch_start_time" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_start_time" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_end_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "worker_type", "operator": "=", "value": "AGG" }
     ]
    }
   ]
  },
  {
   "title": "N2P Overview SPC",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "rule_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "worker_type" ], "type": "tag" }
     ],
     "measurement": "helix_n2p_workers",
     "query": "SELECT \"task_id\", \"wrk_proc_min\", \"wrk_wait_min\" FROM \"monitoring\".\"helix_n2p_workers\" WHERE (\"env\" =~ /^$env$/ AND \"worker_type\" = 'AGG') AND $timeFilter GROUP BY \"env\", \"host\", \"rule_name\", \"state\", \"worker_type\"",
     "select": [
      [
       { "params": [ "task_id" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_proc_min" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_wait_min" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "worker_type", "operator": "=", "value": "SPC" }
     ]
    }
   ]
  },
  {
   "title": "N2P Overview TG",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "rule_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "worker_type" ], "type": "tag" }
     ],
     "measurement": "helix_n2p_workers",
     "query": "SELECT * FROM \"monitoring\".\"helix_n2p_workers\" WHERE (\"env\" =~ /^$env$/ AND \"worker_type\" = 'TG') AND $timeFilter",
     "select": [
      [
       { "params": [ "task_id" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_proc_min" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_wait_min" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "worker_type", "operator": "=", "value": "TG" }
     ]
    }
   ]
  },
  {
   "title": "N2P Overview NORMA",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "rule_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "worker_type" ], "type": "tag" }
     ],
     "measurement": "helix_n2p_workers",
     "query": "SELECT * FROM \"monitoring\".\"helix_n2p_workers\" WHERE (\"env\" =~ /^$env$/ AND \"worker_type\" = 'NORMA') AND $timeFilter",
     "select": [
      [
       { "params": [ "task_id" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_proc_min" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_wait_min" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "worker_type", "operator": "=", "value": "NORMA" }
     ]
    }
   ]
  },
  {
   "title": "N2P Overview THINOUT",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "rule_name" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "worker_type" ], "type": "tag" }
     ],
     "measurement": "helix_n2p_workers",
     "query": "SELECT \"task_id\", \"wrk_proc_min\", \"wrk_wait_min\" FROM \"monitoring\".\"helix_n2p_workers\" WHERE (\"env\" =~ /^$env$/ AND \"worker_type\" = '') AND $timeFilter GROUP BY \"env\", \"host\", \"rule_name\", \"state\", \"worker_type\"",
     "select": [
      [
       { "params": [ "task_id" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_proc_min" ], "type": "field" }
      ],
      [
       { "params": [ "wrk_wait_min" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "worker_type", "operator": "=", "value": "THINOUT" }
     ]
    }
   ]
  },
  { "title": "Core Dumps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Core Stat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "Cores#" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "helix_cores_status",
     "query": "SELECT count(core_size) AS \"Cores#\" FROM \"monitoring\".\"helix_cores_status\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "core_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Cores#" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Core Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "core_dump" ], "type": "tag" },
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "helix_cores_details",
     "select": [
      [
       { "params": [ "cause" ], "type": "field" }
      ],
      [
       { "params": [ "generated_by" ], "type": "field" }
      ],
      [
       { "params": [ "original_core" ], "type": "field" }
      ],
      [
       { "params": [ "signal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Weblogic Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "WLS Heap Size",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "wl_server" ], "type": "tag" },
        { "params": [ "env" ], "type": "tag" },
        { "params": [ "severity" ], "type": "tag" }
       ],
       "measurement": "wls_heap_status",
       "query": "SELECT \"heap_size\" AS \"heap_size_mb\", \"heap_used\" AS \"heap_used_mb\", \"heap_used\" AS \"heap_used_mb\" FROM \"monitoring\".\"wls_heap_status\" WHERE $timeFilter GROUP BY \"wl_server\", \"state\"  ORDER by time DESC",
       "select": [
        [
         { "params": [ "heap_size" ], "type": "field" }
        ],
        [
         { "params": [ "heap_used" ], "type": "field" }
        ],
        [
         { "params": [ "heap_pct" ], "type": "field" }
        ],
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "wl_server", "operator": "=~", "value": "/^$wls$/" }
       ]
      }
     ]
    },
    {
     "title": "WLS Heap Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "Heap (%)" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "wl_server" ], "type": "tag" }
       ],
       "measurement": "wls_heap_status",
       "select": [
        [
         { "params": [ "heap_pct" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "wl_server", "operator": "=~", "value": "/^$wls$/" }
       ]
      }
     ]
    },
    {
     "title": "EAR Queues",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "env" ], "type": "tag" },
        { "params": [ "wl_server" ], "type": "tag" },
        { "params": [ "severity" ], "type": "tag" }
       ],
       "measurement": "wls_queue_status",
       "select": [
        [
         { "params": [ "queue_size" ], "type": "field" }
        ],
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "wl_server", "operator": "=~", "value": "/^$wls$/" }
       ]
      }
     ]
    },
    {
     "title": "EAR Queues",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "wl_server" ], "type": "tag" }
       ],
       "measurement": "wls_queue_status",
       "select": [
        [
         { "params": [ "queue_size" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "env", "operator": "=~", "value": "/^$env$/" },
        { "condition": "AND", "key": "wl_server", "operator": "=~", "value": "/^$wls$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}