{
 "title": "Server Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "show tag values from server_topN with key = \"env\" "
   },
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values from server_topN with key = \"host\"  where env =~ /$env/"
   },
   { "name": "ds", "label": "env", "query": "influxdb" },
   {
    "name": "path",
    "label": "FS Partition",
    "query": "show tag values from disk with key = \"path\"  where env =~ /$env/ and host =~ /$host/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent", "label": "Util (%)" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "params": [ "env" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - \"usage_idle\" as \"CPU Util\" FROM \"monitoring\".\"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"env\" =~ /^$env$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"env\", \"host\"",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Util (%)" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "MEM Util" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "FS Utilization(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Util(%)" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "FS Util %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Util(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Util(%)" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "TopN Consumers",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" }
     ],
     "measurement": "server_topN",
     "query": "SELECT \"state\", \"cpu_pct\", \"mem_pct\", \"rsz\", \"vsz\", \"cmd\" FROM \"monitoring\".\"server_topN\" WHERE (\"env\" =~ /^$env$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"host\", \"pid\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ],
      [
       { "params": [ "cpu_pct" ], "type": "field" }
      ],
      [
       { "params": [ "mem_pct" ], "type": "field" }
      ],
      [
       { "params": [ "rsz" ], "type": "field" }
      ],
      [
       { "params": [ "vsz" ], "type": "field" }
      ],
      [
       { "params": [ "cmd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "server_load",
     "select": [
      [
       { "params": [ "load_1m" ], "type": "field" }
      ],
      [
       { "params": [ "load_5m" ], "type": "field" }
      ],
      [
       { "params": [ "load_15m" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ICMP Scan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "RTT (ms)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "dst_host" ], "type": "tag" },
      { "params": [ "env" ], "type": "tag" }
     ],
     "measurement": "server_icmp_scan",
     "select": [
      [
       { "params": [ "rtt_min" ], "type": "field" }
      ],
      [
       { "params": [ "rtt_avg" ], "type": "field" }
      ],
      [
       { "params": [ "rtt_max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "src_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "severity", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Kernel FD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "server_kfd",
     "query": "SELECT \"alloc_fd\", \"max_permitted_fd\", \"unused_alloc_fd\" FROM \"monitoring\".\"servek_kfd\" WHERE $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "alloc_fd" ], "type": "field" }
      ],
      [
       { "params": [ "max_permitted_fd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "IF Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "iface" ], "type": "tag" }
     ],
     "measurement": "server_ifutil",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "IO Util",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host.$tag_device:$col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "server_ioutil",
     "select": [
      [
       { "params": [ "avgqu_sz" ], "type": "field" }
      ],
      [
       { "params": [ "avgrq_sz" ], "type": "field" }
      ],
      [
       { "params": [ "await" ], "type": "field" }
      ],
      [
       { "params": [ "rd_sec_s" ], "type": "field" }
      ],
      [
       { "params": [ "svctm" ], "type": "field" }
      ],
      [
       { "params": [ "util_pcnt" ], "type": "field" }
      ],
      [
       { "params": [ "wr_sec_s" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}